# Generated by Django 5.0 on 2024-02-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lang_type',
            field=models.CharField(blank=True, choices=[('ko', 'ko'), ('en', 'en'), ('cn', 'cn')], default='en', max_length=10),
        ),
    ]
