apiVersion: 1

datasources:
- name: Postgres
  type: postgres
  access: proxy
  url: postgres:5432
  user: ${POSTGRES_USER}
  secureJsonData:
    password: ${POSTGRES_PASSWORD}
  jsonData:
    database: ${POSTGRES_DB}
    sslmode: 'disable' # disable/require/verify-ca/verify-full
    maxOpenConns: 100 # Grafana v5.4+
    maxIdleConns: 100 # Grafana v5.4+
    maxIdleConnsAuto: true # Grafana v9.5.1+
    connMaxLifetime: 14400 # Grafana v5.4+
    timescaledb: false
- name: Prometheus
  type: prometheus
  access: proxy
  url: https://prometheus:9090
  isDefault: true
  editable: true
  jsonData:
    httpMethod: POST
    manageAlerts: true
    prometheusType: Prometheus
    prometheusVersion: 2.44.0
    cacheLevel: 'High'
    disableRecordingRules: false
    incrementalQueryOverlapWindow: 10m
    tlsSkipVerify: true