apiVersion: 1

datasources:
- name: grafana-postgresql-datasource
  type: postgres
  access: proxy
  database: ${POSTGRES_USER}
  user: ${POSTGRES_USER}
  url: postgres:5432
  secureJsonData:
    password: ${POSTGRES_PASSWORD}
  jsonData:
    postgresVersion: 160
  readOnly: false
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://prometheus:9090
  isDefault: true
  editable: true
