version: "3.8"

services:
  frontend:
    image: ${FRONTEND_IMAGE_NAME}:${FRONTEND_IMAGE_TAG}
    container_name: ${FRONTEND_CONTAINER_NAME}
    build:
      context: ./frontend
    env_file:
      - .env
    stdin_open: true
    tty: true
    working_dir: /src
    ports:
      - 80:80
    volumes:
      - ./frontend:/var/www/html
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - db
      - backend

  backend:
    image: ${BACKEND_IMAGE_NAME}:${BACKEND_IMAGE_TAG}
    container_name: ${BACKEND_CONTAINER_NAME}
    build:
      context: ./backend
    env_file:
      - .env
    stdin_open: true
    tty: true
    working_dir: /src
    ports:
      - 8000:8000
    volumes:
      - ./backend:/src
      - run_vol:/var/run
      - cache_vol:/var/cache
    command: >
      sh -c "sh migrations.sh && python manage.py runserver 0.0.0.0:8000"
    environment:
      - POSTGRES_HOST=${DATABASE_CONTAINER_NAME}
    depends_on:
      - db

  db:
    image: postgres:16.1-alpine3.19
    container_name: ${DATABASE_CONTAINER_NAME}
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - PGUSER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ${DATABASE_VOLUME}:/var/lib/postgresql/data

  game:
    build:
      context: game
      dockerfile: Dockerfile
    image: ${GAME_IMAGE_NAME}:${GAME_IMAGE_TAG}
    pull_policy: never
    container_name: ${GAME_CONTAINER_NAME}
    command: python3 manage.py runserver 0.0.0.0:4444 --nothreading
    restart: always
    volumes:
      - ./game:/src:z
    env_file:
      - .env
    ports:
      - 4444:4444
      - 5555:5555

volumes:
  run_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  cache_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
