# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 15s 


# alertmanager와 프로메테우스를 연결하기 위해 설정 추가
# 현재 로컬에서 9093 포트를 통해 alertmanager가 구동되고 있음
alerting:
  alertmanagers:
    - static_configs:
         - targets:
              - localhost:9090

# 어떤 경우에 알람이 발생할 것인지 규칙을 정해놓은 rules 파일을 설정
rule_files:
  - "alert_rule.yml"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
       - targets: ['localhost:9090']

  - job_name: django
    metrics_path: /monitor/metrics
    static_configs:
      - targets: ['localhost:8000']
        labels:
          app: 'hi'