global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
         - targets:
              - localhost:9090

rule_files:
  - "alert_rule.yml"

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
        - localhost:9090

  - job_name: 'django'
    metrics_path: /monitor/metrics
    scheme: http
    static_configs:
      - targets:
        - localhost:8000